//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.QueueMasters = new HashSet<QueueMaster>();
            this.QueueArchives = new HashSet<QueueArchive>();
        }
    
        public long Id { get; set; }
        public string Email1 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<QueueMaster> QueueMasters { get; set; }
        public virtual ICollection<QueueArchive> QueueArchives { get; set; }
    }
}
