//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueArchive
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Queued { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
        public Nullable<System.Guid> SmptId { get; set; }
        public string Reason { get; set; }
        public Nullable<long> EmailId { get; set; }
        public Nullable<long> MessageId { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Message Message { get; set; }
    }
}
