//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueMaster
    {
        public System.Guid Id { get; set; }
        public int OrganizationId { get; set; }
        public long QueuedNumber { get; set; }
        public System.DateTime QueuedDate { get; set; }
        public bool Processed { get; set; }
        public System.DateTime LastProcessedDate { get; set; }
        public int Attempts { get; set; }
        public bool Retry { get; set; }
        public long EmailId { get; set; }
        public long MessageId { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Message Message { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
