//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long Id { get; set; }
        public Nullable<long> MessageId { get; set; }
        public string EmailAddress { get; set; }
        public bool IsSender { get; set; }
        public bool IsReciever { get; set; }
        public Nullable<bool> isBcc { get; set; }
        public Nullable<bool> isCc { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
