//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueArchive
    {
        public long Id { get; set; }
        public Nullable<System.Guid> QueueId { get; set; }
        public Nullable<long> OrganizationId { get; set; }
        public Nullable<long> QueueOrder { get; set; }
        public Nullable<System.DateTime> QueuedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<bool> Retry { get; set; }
        public Nullable<long> MessageId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Status Status { get; set; }
    }
}
