//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueMaster
    {
        public System.Guid Id { get; set; }
        public long OrganizationId { get; set; }
        public long QueuedOrder { get; set; }
        public Nullable<System.DateTime> QueuedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> Attempts { get; set; }
        public bool Retry { get; set; }
        public long MessageId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Status Status { get; set; }
    }
}
