//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Img.EmailQueue.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.QueueArchives = new HashSet<QueueArchive>();
            this.QueueMasters = new HashSet<QueueMaster>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<QueueArchive> QueueArchives { get; set; }
        public virtual ICollection<QueueMaster> QueueMasters { get; set; }
    }
}
